social_post.post.*:
  type: config_entity
  label: 'Post config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    uuid:
      type: string
    revision:
      type: boolean
      label: 'Whether a new revision should be created by default'
